### ISSUE TITLE
issue with withoutNumericIndices

### ISSUE THREAD

**Issue by nyamsprod** [bpolaszek/querystring#1]
https://github.com/bpolaszek/querystring/blob/58e367324084ede4bf44011f753560ad8bba4204/src/Renderer/ArrayValuesNormalizerRenderer.php#L30

This method can also overrides the parameter values.

**Comment by bpolaszek** [comment]
good catch.

**Comment by bpolaszek** [comment]
Not the prettiest code ever, but it works :sunglasses:

**Comment by nyamsprod** [comment]
https://github.com/thephpleague/uri-components/blob/3b2e7d1d29e916c7e230e617d900cefaa0a9df90/src/Components/Query.php#L644-L684

This is what I did. Didn't want to influence your solution ;)
